package hcmute.vn.entity;
// Generated Nov 17, 2022, 12:16:28 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Commission generated by hbm2java
 */
@Entity
@Table(name = "Commission", schema = "dbo", catalog = "EShop", uniqueConstraints = {
		@UniqueConstraint(columnNames = "cost"), @UniqueConstraint(columnNames = "name") })
@NamedQuery(name = "Commission.findAll", query = "SELECT c FROM Commission c")
public class Commission implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private int id;
	@Column(name = "name", unique = true, nullable = false)

	private String name;
	@Column(name = "cost", unique = true, nullable = false, precision = 10)

	private int cost;
	@Column(name = "description", nullable = false)

	private String description;
	@Column(name = "is_deleted")

	private Boolean isDeleted;
	@Temporal(TemporalType.DATE)
	@Column(name = "createAt", length = 10)
	private Date createAt;

	@Temporal(TemporalType.DATE)
	@Column(name = "updateAt", length = 10)
	private Date updateAt;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commission")

	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Commission() {
	}

	public Commission(String name, int cost, String description) {
		this.name = name;
		this.cost = cost;
		this.description = description;
	}

	public Commission(String name, int cost, String description, Boolean isDeleted, Date createAt, Date updateAt,
			Set<Orders> orderses) {
		this.name = name;
		this.cost = cost;
		this.description = description;
		this.isDeleted = isDeleted;
		this.createAt = createAt;
		this.updateAt = updateAt;
		this.orderses = orderses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
