package hcmute.vn.entity;
// Generated Nov 17, 2022, 12:16:28 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "Product", schema = "dbo", catalog = "EShop", uniqueConstraints = @UniqueConstraint(columnNames = "slug"))
@NamedQuery(name = "Product.findAll", query = "SELECT p FROM Product p")
public class Product implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "storeId")
	private Store store;
	
	@Column(name = "name", nullable = false)
	private String name;
	
	@Column(name = "slug", unique = false)
	private String slug;
	
	@Column(name = "desciption", nullable = true)
	private String desciption;
	
	@Column(name = "price", nullable = false, precision = 10)
	private int price;
	
	@Column(name = "promotionalPrice", nullable = false, precision = 10)
	private int promotionalPrice;
	
	@Column(name = "quantity", nullable = false)
	private int quantity;
	
	@Column(name = "slod")
	private Integer slod;
	
	@Column(name = "is_active")
	private Boolean isActive;
	
	@Column(name = "is_selling")
	private Boolean isSelling;
	
	@Column(name = "listImage")
	private String listImage;
	
	@Column(name = "categoryId")
	private Integer categoryId;
	
	@Column(name = "style_valueIds")
	private String styleValueIds;
	
	@Column(name = "rating")
	private int rating;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "createAt", length = 10)
	private Date createAt;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "updateAt", length = 10)
	private Date updateAt;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	private Set<UserFollowProduct> userFollowProducts = new HashSet<UserFollowProduct>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	private Set<CartItem> cartItems = new HashSet<CartItem>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);

	public Product() {
		
	}
	

	public Product(String name, String desciption, int price, int promotionalPrice,
			int quantity) {
		this.name = name;
		this.desciption = desciption;
		this.price = price;
		this.promotionalPrice = promotionalPrice;
		this.quantity = quantity;
	}

	public Product(Store store, String name, String slug, String desciption, int price,
			int promotionalPrice, int quantity, Integer slod, Boolean isActive, Boolean isSelling,
			String listImage, Integer categoryId, String styleValueIds, Integer rating, Date createAt,
			Date updateAt, Set<UserFollowProduct> userFollowProducts, Set<CartItem> cartItems,
			Set<OrderItem> orderItems) {
		this.store = store;
		this.name = name;
		this.slug = slug;
		this.desciption = desciption;
		this.price = price;
		this.promotionalPrice = promotionalPrice;
		this.quantity = quantity;
		this.slod = slod;
		this.isActive = isActive;
		this.isSelling = isSelling;
		this.listImage = listImage;
		this.categoryId = categoryId;
		this.styleValueIds = styleValueIds;
		this.rating = rating;
		this.createAt = createAt;
		this.updateAt = updateAt;
		this.userFollowProducts = userFollowProducts;
		this.cartItems = cartItems;
		this.orderItems = orderItems;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public String getDesciption() {
		return this.desciption;
	}

	public void setDesciption(String desciption) {
		this.desciption = desciption;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getPromotionalPrice() {
		return this.promotionalPrice;
	}

	public void setPromotionalPrice(int promotionalPrice) {
		this.promotionalPrice = promotionalPrice;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Integer getSlod() {
		return this.slod;
	}

	public void setSlod(Integer slod) {
		this.slod = slod;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Boolean getIsSelling() {
		return this.isSelling;
	}

	public void setIsSelling(Boolean isSelling) {
		this.isSelling = isSelling;
	}

	public String getListImage() {
		return this.listImage;
	}

	public void setListImage(String listImage) {
		this.listImage = listImage;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getStyleValueIds() {
		return this.styleValueIds;
	}

	public void setStyleValueIds(String styleValueIds) {
		this.styleValueIds = styleValueIds;
	}

	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	
	public Set<UserFollowProduct> getUserFollowProducts() {
		return this.userFollowProducts;
	}

	public void setUserFollowProducts(Set<UserFollowProduct> userFollowProducts) {
		this.userFollowProducts = userFollowProducts;
	}

	public Set<CartItem> getCartItems() {
		return this.cartItems;
	}

	public void setCartItems(Set<CartItem> cartItems) {
		this.cartItems = cartItems;
	}

	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

}
