package hcmute.vn.entity;
// Generated Nov 17, 2022, 12:16:28 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Delivery generated by hbm2java
 */
@Entity
@Table(name = "Review", schema = "dbo", catalog = "EShop")
public class Review implements java.io.Serializable {

    private Integer id;
    private Users user;
    private Product product;
    private Store store;
    private Orders order;
    private String content;
    private int stars;
    private Date createAt;
    private Date updateAt;


    public Review() {
    }

    public Review(Users users, Product product, Store store, Orders order, String content, int stars) {
        this.user = users;
        this.product = product;
        this.store = store;
        this.order = order;
        this.content = content;
        this.stars = stars;
        this.createAt = new Date();
        this.updateAt = new Date();
    }


    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    public Users getUser() {
        return this.user;
    }

    public void setUser(Users user) {
        this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    public Product getProduct() {return this.product;}

    public void setProduct(Product product) {this.product = product;}

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "store_id", nullable = false)
    public Store getStore() {return this.store;}

    public void setStore(Store store) {this.store = store;}

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    public Orders getOrder() {return this.order;}

    public void setOrder(Orders order) {this.order = order;}

    @Column(name = "content", nullable = false)
    public String getContent() {return this.content;}

    public void setContent(String content) {this.content = content;}

    @Column(name = "stars", nullable = false)
    public int getStars() {return this.stars;}

    public void setStars(int stars) {this.stars = stars;}


    @Temporal(TemporalType.DATE)
    @Column(name = "createAt", length = 10)
    public Date getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "updateAt", length = 10)
    public Date getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

}
