package hcmute.vn.entity;
// Generated Nov 17, 2022, 12:16:28 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * StoreLevel generated by hbm2java
 */
@Entity
@Table(name = "StoreLevel", schema = "dbo", catalog = "EShop")
public class StoreLevel implements java.io.Serializable {

	private Integer id;
	private Store store;
	private Serializable name;
	private int minPoint;
	private BigDecimal discount;
	private Boolean isDelete;
	private Date createAt;
	private Date updateAt;

	public StoreLevel() {
	}

	public StoreLevel(Store store, Serializable name, int minPoint, BigDecimal discount) {
		this.store = store;
		this.name = name;
		this.minPoint = minPoint;
		this.discount = discount;
	}

	public StoreLevel(Store store, Serializable name, int minPoint, BigDecimal discount, Boolean isDelete,
			Date createAt, Date updateAt) {
		this.store = store;
		this.name = name;
		this.minPoint = minPoint;
		this.discount = discount;
		this.isDelete = isDelete;
		this.createAt = createAt;
		this.updateAt = updateAt;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "store"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@Column(name = "name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "minPoint", nullable = false)
	public int getMinPoint() {
		return this.minPoint;
	}

	public void setMinPoint(int minPoint) {
		this.minPoint = minPoint;
	}

	@Column(name = "discount", nullable = false, precision = 10)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "is_delete")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createAt", length = 10)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updateAt", length = 10)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

}
