package hcmute.vn.entity;
// Generated Nov 17, 2022, 12:16:28 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Style generated by hbm2java
 */
@Entity
@Table(name = "Style", schema = "dbo", catalog = "EShop", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
@NamedQuery(name = "Style.findAll", query = "SELECT s FROM Style s")

public class Style implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_ids")
	private Category category;
	@Column(name = "name", unique = true, nullable = false)

	private String name;
	@Column(name = "is_deleted")

	private Boolean isDeleted;
	@Temporal(TemporalType.DATE)
	@Column(name = "createAt", length = 10)
	private Date createAt;
	@Temporal(TemporalType.DATE)
	@Column(name = "updateAt", length = 10)
	private Date updateAt;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "style")
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "style")
	private Set<CartItem> cartItems = new HashSet<CartItem>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "style")
	private Set<StyleValue> styleValues = new HashSet<StyleValue>(0);

	public Style() {
	}

	public Style(String name) {
		this.name = name;
	}

	public Style(Category category, String name, Boolean isDeleted, Date createAt, Date updateAt,
			Set<OrderItem> orderItems, Set<CartItem> cartItems, Set<StyleValue> styleValues) {
		this.category = category;
		this.name = name;
		this.isDeleted = isDeleted;
		this.createAt = createAt;
		this.updateAt = updateAt;
		this.orderItems = orderItems;
		this.cartItems = cartItems;
		this.styleValues = styleValues;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}


	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	public Set<CartItem> getCartItems() {
		return this.cartItems;
	}

	public void setCartItems(Set<CartItem> cartItems) {
		this.cartItems = cartItems;
	}

	public Set<StyleValue> getStyleValues() {
		return this.styleValues;
	}

	public void setStyleValues(Set<StyleValue> styleValues) {
		this.styleValues = styleValues;
	}

}
