package hcmute.vn.entity;
// Generated Nov 17, 2022, 12:16:28 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "Users", schema = "dbo", catalog = "EShop", uniqueConstraints = { @UniqueConstraint(columnNames = "slug"),
		@UniqueConstraint(columnNames = "email"), @UniqueConstraint(columnNames = "phone"),
		@UniqueConstraint(columnNames = "id_card") })
public class Users implements java.io.Serializable {

	private Integer id;
	private Serializable firstName;
	private Serializable lastName;
	private Serializable slug;
	private Serializable idCard;
	private Serializable email;
	private String phone;
	private Boolean isEmailActive;
	private Boolean isPhoneActive;
	private Serializable hashedPassword;
	private Boolean role;
	private Serializable addresses;
	private String avatar;
	private String cover;
	private Integer point;
	private BigDecimal EWallet;
	private Date createAt;
	private Date updateAt;
	private Set<Transactions> transactionses = new HashSet<Transactions>(0);
	private Set<UserFollowProduct> userFollowProducts = new HashSet<UserFollowProduct>(0);
	private Set<Cart> carts = new HashSet<Cart>(0);
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<Store> stores = new HashSet<Store>(0);
	private Set<UserFollowStore> userFollowStores = new HashSet<UserFollowStore>(0);
	private UserLevel userLevel;

	public Users() {
	}

	public Users(Serializable firstName, Serializable lastName, Serializable hashedPassword) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.hashedPassword = hashedPassword;
	}

	public Users(Serializable firstName, Serializable lastName, Serializable slug, Serializable idCard,
			Serializable email, String phone, Boolean isEmailActive, Boolean isPhoneActive, Serializable hashedPassword,
			Boolean role, Serializable addresses, String avatar, String cover, Integer point, BigDecimal EWallet,
			Date createAt, Date updateAt, Set<Transactions> transactionses, Set<UserFollowProduct> userFollowProducts,
			Set<Cart> carts, Set<Orders> orderses, Set<Store> stores, Set<UserFollowStore> userFollowStores,
			UserLevel userLevel) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.slug = slug;
		this.idCard = idCard;
		this.email = email;
		this.phone = phone;
		this.isEmailActive = isEmailActive;
		this.isPhoneActive = isPhoneActive;
		this.hashedPassword = hashedPassword;
		this.role = role;
		this.addresses = addresses;
		this.avatar = avatar;
		this.cover = cover;
		this.point = point;
		this.EWallet = EWallet;
		this.createAt = createAt;
		this.updateAt = updateAt;
		this.transactionses = transactionses;
		this.userFollowProducts = userFollowProducts;
		this.carts = carts;
		this.orderses = orderses;
		this.stores = stores;
		this.userFollowStores = userFollowStores;
		this.userLevel = userLevel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstName", nullable = false)
	public Serializable getFirstName() {
		return this.firstName;
	}

	public void setFirstName(Serializable firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false)
	public Serializable getLastName() {
		return this.lastName;
	}

	public void setLastName(Serializable lastName) {
		this.lastName = lastName;
	}

	@Column(name = "slug", unique = true)
	public Serializable getSlug() {
		return this.slug;
	}

	public void setSlug(Serializable slug) {
		this.slug = slug;
	}

	@Column(name = "id_card", unique = true)
	public Serializable getIdCard() {
		return this.idCard;
	}

	public void setIdCard(Serializable idCard) {
		this.idCard = idCard;
	}

	@Column(name = "email", unique = true)
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Column(name = "phone", unique = true, length = 30)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "isEmailActive")
	public Boolean getIsEmailActive() {
		return this.isEmailActive;
	}

	public void setIsEmailActive(Boolean isEmailActive) {
		this.isEmailActive = isEmailActive;
	}

	@Column(name = "isPhoneActive")
	public Boolean getIsPhoneActive() {
		return this.isPhoneActive;
	}

	public void setIsPhoneActive(Boolean isPhoneActive) {
		this.isPhoneActive = isPhoneActive;
	}

	@Column(name = "hashed_password", nullable = false)
	public Serializable getHashedPassword() {
		return this.hashedPassword;
	}

	public void setHashedPassword(Serializable hashedPassword) {
		this.hashedPassword = hashedPassword;
	}

	@Column(name = "role")
	public Boolean getRole() {
		return this.role;
	}

	public void setRole(Boolean role) {
		this.role = role;
	}

	@Column(name = "addresses")
	public Serializable getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Serializable addresses) {
		this.addresses = addresses;
	}

	@Column(name = "avatar", length = 100)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "cover", length = 100)
	public String getCover() {
		return this.cover;
	}

	public void setCover(String cover) {
		this.cover = cover;
	}

	@Column(name = "point")
	public Integer getPoint() {
		return this.point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}

	@Column(name = "e_wallet", precision = 10)
	public BigDecimal getEWallet() {
		return this.EWallet;
	}

	public void setEWallet(BigDecimal EWallet) {
		this.EWallet = EWallet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createAt", length = 10)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updateAt", length = 10)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Transactions> getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set<Transactions> transactionses) {
		this.transactionses = transactionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserFollowProduct> getUserFollowProducts() {
		return this.userFollowProducts;
	}

	public void setUserFollowProducts(Set<UserFollowProduct> userFollowProducts) {
		this.userFollowProducts = userFollowProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Store> getStores() {
		return this.stores;
	}

	public void setStores(Set<Store> stores) {
		this.stores = stores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserFollowStore> getUserFollowStores() {
		return this.userFollowStores;
	}

	public void setUserFollowStores(Set<UserFollowStore> userFollowStores) {
		this.userFollowStores = userFollowStores;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "users")
	public UserLevel getUserLevel() {
		return this.userLevel;
	}

	public void setUserLevel(UserLevel userLevel) {
		this.userLevel = userLevel;
	}

}
